export enum Category {
    Arrow = 'arrow',
    Brand = 'brand',
    Business = 'business',
    Chat = 'chat',
    ComputerScience = 'computer science',
    DateAndTime = 'date & time',
    Emoticon = 'emoticon',
    Health= 'health',
    HotelAndHousing = 'hotel & housing',
    ImageAndVideo = 'image & video',
    Mathematics = 'mathematics',
    Mechanics = 'mechanics',
    Multimedia = 'multimedia',
    Music = 'music',
    Shopping = 'shopping',
    Social = 'social',
    Object = 'object',
    Other = 'other',
    Technology = 'technology',
    VideoGame = 'video game',
    Weather = 'weather',
    Writing = 'writing'
}
